function Download_TLE(norad,filename,datestart,datestop,username,password)
% startdate = '2000-01-01';
% enddate = '2017-09-03';

URL='https://www.space-track.org/ajaxauth/login';

link = ['https://www.space-track.org/basicspacedata/',...
    'query/class/tle/',...
    'EPOCH/',datestart,'--',datestop,'/NORAD_CAT_ID/',num2str(norad),'/',...
    'orderby/TLE_LINE1 ASC/format/tle'];

post={...
  'identity',username,...
  'password',password,...
  'query',link...
};

urlwrite(URL,filename,'Post',post,'Timeout',20);
pause(5);

end